BEGIN;

TRUNCATE TABLE feedback RESTART IDENTITY CASCADE;
TRUNCATE TABLE favorite RESTART IDENTITY CASCADE;
TRUNCATE TABLE progress RESTART IDENTITY CASCADE;
TRUNCATE TABLE history RESTART IDENTITY CASCADE;
TRUNCATE TABLE tag_to_video RESTART IDENTITY CASCADE;
TRUNCATE TABLE tag RESTART IDENTITY CASCADE;
TRUNCATE TABLE track RESTART IDENTITY CASCADE;
TRUNCATE TABLE video RESTART IDENTITY CASCADE;
TRUNCATE TABLE category RESTART IDENTITY CASCADE;
TRUNCATE TABLE learner RESTART IDENTITY CASCADE;
TRUNCATE TABLE account RESTART IDENTITY CASCADE;

COMMIT;
